singleQuote: true
printWidth: 80
semi: true

plugins:
  - prettier-plugin-astro

overrides:
  - files: '*.astro'
    options:
      parser: 'astro'
  - files: '*.{md,mdx}'
    options:
      printWidth: 80
  - files: 'projects/**/*.html'
    options:
      parser: angular
