name: NPM Publish

env:
  NODE_VERSION: 20

on:
  release:
    types: [created]

jobs:
  test-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: npm

      - run: npm ci

      - run: npm run build:lib
      - run: npm run test:lib

  publish-github-packages:
    needs: test-lib
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: https://npm.pkg.github.com/

      - run: npm ci
      - run: npm run build:lib

      - run: npm publish dist/ngx-editor/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
